"""Tests for dependency constraint files (item 4.3).

Ensures constraints.txt and constraints-all.txt exist and pin every direct
dependency listed in requirements_base.txt and requirements_dev.txt
respectively, providing a reproducible build surface for deployable images.
"""

from __future__ import annotations

import re
from pathlib import Path

_ROOT = Path(__file__).parent.parent
_CONSTRAINTS = _ROOT / "constraints.txt"
_CONSTRAINTS_ALL = _ROOT / "constraints-all.txt"
_REQS_BASE = _ROOT / "media_service" / "requirements_base.txt"
_REQS_DEV = _ROOT / "media_service" / "requirements_dev.txt"

# Matches a pip-compile header comment line.
_HEADER_RE = re.compile(r"^#\s*This file is autogenerated by pip-compile", re.MULTILINE)
# Matches a bare package name from a requirements line (strips version specifier,
# options, and comments).
_PKG_NAME_RE = re.compile(r"^([A-Za-z0-9]([A-Za-z0-9._-]*[A-Za-z0-9])?)", re.IGNORECASE)
# Package name normalisation: treat `-` and `_` as equivalent (PEP 503).
_NORM_RE = re.compile(r"[-_.]+")
# pip-compile marks these as "unsafe" and intentionally omits them.
_PIP_COMPILE_UNSAFE = frozenset(["pip", "setuptools", "wheel"])


def _normalize(name: str) -> str:
    return _NORM_RE.sub("-", name).lower()


def _direct_packages(req_file: Path) -> set[str]:
    """Extract normalised package names from a requirements file.

    Skips option lines (``-r``, ``-c``, ``--...``), comments, and empty lines.
    """
    packages: set[str] = set()
    for line in req_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("-"):
            continue
        m = _PKG_NAME_RE.match(line)
        if m:
            packages.add(_normalize(m.group(1)))
    return packages


def _pinned_packages(constraints_file: Path) -> set[str]:
    """Return normalised package names that appear as pins (``name==version``)."""
    packages: set[str] = set()
    for line in constraints_file.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = _PKG_NAME_RE.match(line)
        if m:
            packages.add(_normalize(m.group(1)))
    return packages


class TestConstraintsFile:
    """constraints.txt: autogenerated, present, and covers requirements_base.txt."""

    def test_constraints_file_exists(self):
        assert _CONSTRAINTS.exists(), (
            f"constraints.txt not found at {_CONSTRAINTS}. "
            "Regenerate with: pip-compile --no-emit-index-url "
            "--output-file=constraints.txt media_service/requirements_base.txt"
        )

    def test_constraints_file_is_autogenerated(self):
        content = _CONSTRAINTS.read_text()
        assert _HEADER_RE.search(content), (
            "constraints.txt does not contain the pip-compile autogeneration "
            "header — it may have been hand-edited."
        )

    def test_constraints_pins_all_base_requirements(self):
        direct = _direct_packages(_REQS_BASE)
        pinned = _pinned_packages(_CONSTRAINTS)
        missing = direct - pinned
        assert not missing, (
            "constraints.txt does not pin the following packages from "
            f"requirements_base.txt: {sorted(missing)}. "
            "Regenerate with: pip-compile --no-emit-index-url "
            "--output-file=constraints.txt media_service/requirements_base.txt"
        )


class TestConstraintsAllFile:
    """constraints-all.txt: autogenerated, present, and covers requirements_dev.txt."""

    def test_constraints_all_file_exists(self):
        assert _CONSTRAINTS_ALL.exists(), (
            f"constraints-all.txt not found at {_CONSTRAINTS_ALL}. "
            "Regenerate with: pip-compile --no-emit-index-url "
            "--output-file=constraints-all.txt media_service/requirements_dev.txt"
        )

    def test_constraints_all_file_is_autogenerated(self):
        content = _CONSTRAINTS_ALL.read_text()
        assert _HEADER_RE.search(content), (
            "constraints-all.txt does not contain the pip-compile autogeneration header."
        )

    def test_constraints_all_pins_all_dev_requirements(self):
        direct = _direct_packages(_REQS_DEV) - _PIP_COMPILE_UNSAFE
        pinned = _pinned_packages(_CONSTRAINTS_ALL)
        missing = direct - pinned
        assert not missing, (
            "constraints-all.txt does not pin the following packages from "
            f"requirements_dev.txt: {sorted(missing)}. "
            "Regenerate with: pip-compile --no-emit-index-url "
            "--output-file=constraints-all.txt media_service/requirements_dev.txt"
        )
