"""Initial m8 migration

Revision ID: b72c1afe45cb
Revises: 
Create Date: 2026-06-22 21:35:31.319128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import media_service.core.db_models

# revision identifiers, used by Alembic.
revision: str = 'b72c1afe45cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_category',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', media_service.core.db_models.UUIDString(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('slug', name='uq_category_slug'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_category_id'), 'app_category', ['id'], unique=False)
    op.create_index(op.f('ix_app_category_owner_id'), 'app_category', ['owner_id'], unique=False)
    op.create_table('app_image_preset',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'tenant_id', 'name', name='uq_image_preset_scope_name'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_image_preset_id'), 'app_image_preset', ['id'], unique=False)
    op.create_index(op.f('ix_app_image_preset_name'), 'app_image_preset', ['name'], unique=False)
    op.create_index(op.f('ix_app_image_preset_owner_user_id'), 'app_image_preset', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_app_image_preset_tenant_id'), 'app_image_preset', ['tenant_id'], unique=False)
    op.create_table('app_media_object',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('storage_bucket', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('storage_class', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scan_status', sa.String(length=32), nullable=False),
    sa.Column('moderation_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_bucket', 'object_key', name='uq_media_object_key'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_media_object_category'), 'app_media_object', ['category'], unique=False)
    op.create_index(op.f('ix_app_media_object_id'), 'app_media_object', ['id'], unique=False)
    op.create_index(op.f('ix_app_media_object_mime_type'), 'app_media_object', ['mime_type'], unique=False)
    op.create_index(op.f('ix_app_media_object_moderation_status'), 'app_media_object', ['moderation_status'], unique=False)
    op.create_index(op.f('ix_app_media_object_object_key'), 'app_media_object', ['object_key'], unique=False)
    op.create_index(op.f('ix_app_media_object_owner_user_id'), 'app_media_object', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_app_media_object_scan_status'), 'app_media_object', ['scan_status'], unique=False)
    op.create_index(op.f('ix_app_media_object_sha256'), 'app_media_object', ['sha256'], unique=False)
    op.create_index(op.f('ix_app_media_object_status'), 'app_media_object', ['status'], unique=False)
    op.create_index(op.f('ix_app_media_object_storage_bucket'), 'app_media_object', ['storage_bucket'], unique=False)
    op.create_index(op.f('ix_app_media_object_tenant_id'), 'app_media_object', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_app_media_object_visibility'), 'app_media_object', ['visibility'], unique=False)
    op.create_table('app_outbox_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_outbox_event_event_type'), 'app_outbox_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_app_outbox_event_id'), 'app_outbox_event', ['id'], unique=False)
    op.create_index(op.f('ix_app_outbox_event_next_attempt_at'), 'app_outbox_event', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_app_outbox_event_object_id'), 'app_outbox_event', ['object_id'], unique=False)
    op.create_index(op.f('ix_app_outbox_event_status'), 'app_outbox_event', ['status'], unique=False)
    op.create_table('app_storage_usage',
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('object_count', sa.BigInteger(), nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=True),
    sa.Column('quota_objects', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'tenant_id', name='uq_storage_usage_scope'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_storage_usage_id'), 'app_storage_usage', ['id'], unique=False)
    op.create_index(op.f('ix_app_storage_usage_owner_user_id'), 'app_storage_usage', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_app_storage_usage_tenant_id'), 'app_storage_usage', ['tenant_id'], unique=False)
    op.create_table('app_subscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_subscription_active'), 'app_subscription', ['active'], unique=False)
    op.create_index(op.f('ix_app_subscription_id'), 'app_subscription', ['id'], unique=False)
    op.create_table('app_upload_session',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('storage_bucket', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('expected_mime_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expected_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_bucket', 'object_key', name='uq_upload_session_key'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_upload_session_category'), 'app_upload_session', ['category'], unique=False)
    op.create_index(op.f('ix_app_upload_session_id'), 'app_upload_session', ['id'], unique=False)
    op.create_index(op.f('ix_app_upload_session_object_key'), 'app_upload_session', ['object_key'], unique=False)
    op.create_index(op.f('ix_app_upload_session_owner_user_id'), 'app_upload_session', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_app_upload_session_status'), 'app_upload_session', ['status'], unique=False)
    op.create_index(op.f('ix_app_upload_session_storage_bucket'), 'app_upload_session', ['storage_bucket'], unique=False)
    op.create_index(op.f('ix_app_upload_session_tenant_id'), 'app_upload_session', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_app_upload_session_visibility'), 'app_upload_session', ['visibility'], unique=False)
    op.create_table('app_media_variant',
    sa.Column('media_object_id', sa.Uuid(), nullable=False),
    sa.Column('variant_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('storage_bucket', sqlmodel.sql.sqltypes.AutoString(length=63), nullable=False),
    sa.Column('object_key', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_object_id'], ['app_media_object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('media_object_id', 'variant_name', name='uq_media_variant_name'),
    sa.UniqueConstraint('storage_bucket', 'object_key', name='uq_media_variant_key'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_media_variant_id'), 'app_media_variant', ['id'], unique=False)
    op.create_index(op.f('ix_app_media_variant_media_object_id'), 'app_media_variant', ['media_object_id'], unique=False)
    op.create_index(op.f('ix_app_media_variant_variant_name'), 'app_media_variant', ['variant_name'], unique=False)
    op.create_table('app_share_token',
    sa.Column('media_object_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_object_id'], ['app_media_object.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_share_token_id'), 'app_share_token', ['id'], unique=False)
    op.create_index(op.f('ix_app_share_token_media_object_id'), 'app_share_token', ['media_object_id'], unique=False)
    op.create_index(op.f('ix_app_share_token_owner_user_id'), 'app_share_token', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_app_share_token_tenant_id'), 'app_share_token', ['tenant_id'], unique=False)
    op.create_table('app_variant_job',
    sa.Column('media_object_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_presets', sa.JSON(), nullable=False),
    sa.Column('variants_expected', sa.Integer(), nullable=False),
    sa.Column('variants_created', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_object_id'], ['app_media_object.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_app_variant_job_id'), 'app_variant_job', ['id'], unique=False)
    op.create_index(op.f('ix_app_variant_job_media_object_id'), 'app_variant_job', ['media_object_id'], unique=False)
    op.create_index(op.f('ix_app_variant_job_owner_user_id'), 'app_variant_job', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_app_variant_job_status'), 'app_variant_job', ['status'], unique=False)
    op.create_index(op.f('ix_app_variant_job_tenant_id'), 'app_variant_job', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_variant_job_tenant_id'), table_name='app_variant_job')
    op.drop_index(op.f('ix_app_variant_job_status'), table_name='app_variant_job')
    op.drop_index(op.f('ix_app_variant_job_owner_user_id'), table_name='app_variant_job')
    op.drop_index(op.f('ix_app_variant_job_media_object_id'), table_name='app_variant_job')
    op.drop_index(op.f('ix_app_variant_job_id'), table_name='app_variant_job')
    op.drop_table('app_variant_job')
    op.drop_index(op.f('ix_app_share_token_tenant_id'), table_name='app_share_token')
    op.drop_index(op.f('ix_app_share_token_owner_user_id'), table_name='app_share_token')
    op.drop_index(op.f('ix_app_share_token_media_object_id'), table_name='app_share_token')
    op.drop_index(op.f('ix_app_share_token_id'), table_name='app_share_token')
    op.drop_table('app_share_token')
    op.drop_index(op.f('ix_app_media_variant_variant_name'), table_name='app_media_variant')
    op.drop_index(op.f('ix_app_media_variant_media_object_id'), table_name='app_media_variant')
    op.drop_index(op.f('ix_app_media_variant_id'), table_name='app_media_variant')
    op.drop_table('app_media_variant')
    op.drop_index(op.f('ix_app_upload_session_visibility'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_tenant_id'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_storage_bucket'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_status'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_owner_user_id'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_object_key'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_id'), table_name='app_upload_session')
    op.drop_index(op.f('ix_app_upload_session_category'), table_name='app_upload_session')
    op.drop_table('app_upload_session')
    op.drop_index(op.f('ix_app_subscription_id'), table_name='app_subscription')
    op.drop_index(op.f('ix_app_subscription_active'), table_name='app_subscription')
    op.drop_table('app_subscription')
    op.drop_index(op.f('ix_app_storage_usage_tenant_id'), table_name='app_storage_usage')
    op.drop_index(op.f('ix_app_storage_usage_owner_user_id'), table_name='app_storage_usage')
    op.drop_index(op.f('ix_app_storage_usage_id'), table_name='app_storage_usage')
    op.drop_table('app_storage_usage')
    op.drop_index(op.f('ix_app_outbox_event_status'), table_name='app_outbox_event')
    op.drop_index(op.f('ix_app_outbox_event_object_id'), table_name='app_outbox_event')
    op.drop_index(op.f('ix_app_outbox_event_next_attempt_at'), table_name='app_outbox_event')
    op.drop_index(op.f('ix_app_outbox_event_id'), table_name='app_outbox_event')
    op.drop_index(op.f('ix_app_outbox_event_event_type'), table_name='app_outbox_event')
    op.drop_table('app_outbox_event')
    op.drop_index(op.f('ix_app_media_object_visibility'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_tenant_id'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_storage_bucket'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_status'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_sha256'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_scan_status'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_owner_user_id'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_object_key'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_moderation_status'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_mime_type'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_id'), table_name='app_media_object')
    op.drop_index(op.f('ix_app_media_object_category'), table_name='app_media_object')
    op.drop_table('app_media_object')
    op.drop_index(op.f('ix_app_image_preset_tenant_id'), table_name='app_image_preset')
    op.drop_index(op.f('ix_app_image_preset_owner_user_id'), table_name='app_image_preset')
    op.drop_index(op.f('ix_app_image_preset_name'), table_name='app_image_preset')
    op.drop_index(op.f('ix_app_image_preset_id'), table_name='app_image_preset')
    op.drop_table('app_image_preset')
    op.drop_index(op.f('ix_app_category_owner_id'), table_name='app_category')
    op.drop_index(op.f('ix_app_category_id'), table_name='app_category')
    op.drop_table('app_category')
    # ### end Alembic commands ###
